import re

file_path = "/Users/ra/Documents/Cementery/Assets/Scripts/Environment/DesertTerrainChunk.cs"
with open(file_path, 'r') as f:
    content = f.read()

# Remove Biome Settings fields
content = re.sub(r'        \[Header\("Biome Settings"\)\].*?\[Header\("Minecraft-style Hilly Terrain \(MC风凹凸峡谷丘陵\)"\)\]', '        [Header("Minecraft-style Hilly Terrain (MC风凹凸峡谷丘陵)")]', content, flags=re.DOTALL)

# Remove RegenerateBiomeColors method
content = re.sub(r'        /// <summary>\s*/// Regenerates and bakes ONLY the biome colors.*?public float GetVertexHeightAtLocal', '        public float GetVertexHeightAtLocal', content, flags=re.DOTALL)

# Remove Biome color generation from GenerateSeamlessMesh
mesh_old = r"""            Color\[\] colors = new Color\[vw \* vd\];.*?Mesh mesh = new Mesh \{ name = "DesertTerrainChunk" \};"""
mesh_new = r"""            Color[] colors = new Color[vw * vd];
            // Colors will be generated by the Global Biome Tool. For now, default to zero alpha.
            for (int i = 0; i < colors.Length; i++) colors[i] = new Color(1, 1, 1, 0);

            Mesh mesh = new Mesh { name = "DesertTerrainChunk" };"""
content = re.sub(mesh_old, mesh_new, content, flags=re.DOTALL)

with open(file_path, 'w') as f:
    f.write(content)
